version: '3.4'

services:
  mysql-database:
    container_name: flask_database
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"

    #This specifies that the container should use a persistent volume at /mysql-data
    #Otherwise, the container will create a new volume on each run and lose data
    volumes:
      - ./mysql-data:/var/lib/mysql
  flask-app:
    container_name: flask_app
    depends_on:
      - mysql-database

    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: default
      DB_HOST: mysql

    #Builds the image from the Dockerfile in the current directory
    build: .

    #Shares the container volume with the host so code changes are immediately available
    volumes:
      - '.:/app'
    ports:
      - "5000:5000"
  react-frontend:
    container_name: react_front

    #Builds the image from the Dockerfile in the current directory
    build: ./src/frontend

    #Shares the container volume with the host so code changes are immediately available
    volumes:
      - './src/frontend/:/src/frontend/'
    ports:
      - "3000:3000"